import { Skeleton } from '@chakra-ui/react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Skeleton>
        <div>contents wrapped</div>
        <div>wont be visible</div>
      </Skeleton>
    </div>
  )
}
export default Home
